// lab1-oracle/react-codebase/src/App.js
import logo from "./logo.svg";
import "./App.css";
import Web3 from "web3";

var abi = [
    {
        "inputs": [
            {
                "internalType": "bytes4",
                "name": "symbol",
                "type": "bytes4"
            },
            {
                "internalType": "uint256",
                "name": "price",
                "type": "uint256"
            },
            {
                "internalType": "uint256",
                "name": "volume",
                "type": "uint256"
            }
        ],
        "name": "setStock",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [],
        "stateMutability": "nonpayable",
        "type": "constructor"
    },
    {
        "inputs": [
            {
                "internalType": "bytes4",
                "name": "symbol",
                "type": "bytes4"
            }
        ],
        "name": "getStockPrice",
        "outputs": [
            {
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            {
                "internalType": "bytes4",
                "name": "symbol",
                "type": "bytes4"
            }
        ],
        "name": "getStockVolume",
        "outputs": [
            {
                "internalType": "uint256",
                "name": "",
                "type": "uint256"
            }
        ],
        "stateMutability": "view",
        "type": "function"
    }
]

var ganacheUrl = "HTTP://127.0.0.1:7545";


function App(){

    async function clickHandler(e){
        e.preventDefault();
        let provider = new Web3(new Web3.providers.HttpProvider(ganacheUrl));
        provider.eth.getAccounts((error, result) => {
            console.log("Address", result);
        });
        //From metamask
        let AddressOwner = "0x6E76fdccaC3886A73F5A8ADDf2D95d627aC05283";
        //From Remix
        let contractAddress = "0x167f03231e54031Cb582d4c3c728f4555a982b3C";
        let contractInstance = new provider.eth.Contract(abi, contractAddress);
        console.log("Contract instance", contractInstance);

        let result = await fetch("http://localhost:3001/");
        let json = await result.json();
        console.log(`Price: ${json.price}`);
        console.log(`Volume: ${json.volume}`);

        //Call the contract to set a stock
        let symbol = "0x6a6f79";
        contractInstance.methods.setStock(symbol, parseInt(json.price), parseInt(json.volume)).send({from: AddressOwner}).on('receipt', () => {
            console.log("set stock values");
        });

        //Call the contract to get the stock price
        contractInstance.methods.getStockPrice(symbol).send({from: AddressOwner}).then(val => {
            console.log("stock price", val);
        });

        //Call the contract to get the stock volume
        contractInstance.methods.getStockVolume(symbol).send({from: AddressOwner}).then(val => {
            console.log("stock volume", val);
        });
    }
    return(
        <div className="App">
            <button onClick={clickHandler}> Click me! </button>
        </div>
    );
}

export default App;

// lab2-ipfs/src/App.vue
<template>
  <v-app>
    <v-app-bar app color="primary" dark>
      <v-spacer></v-spacer>
    </v-app-bar>
    <v-main>
      <v-container>
        <v-btn @click="oracleUpdate">Deploy Oracle</v-btn>
      </v-container>
    </v-main>
  </v-app>
</template>

<script>
import Web3 from "web3";

export default {
  name: "App",
  data() {
    return {
      abi: [
        {
          inputs: [
            {
              internalType: "uint256",
              name: "customerId",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "serialNumber",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "mpxn",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "totalUnits",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "lastMeterRead",
              type: "uint256",
            },
          ],
          name: "setMeterReading",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "customerId",
              type: "uint256",
            },
          ],
          name: "getLastMeterRead",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "customerId",
              type: "uint256",
            },
          ],
          name: "getMpxn",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "customerId",
              type: "uint256",
            },
          ],
          name: "getSerialNumber",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "customerId",
              type: "uint256",
            },
          ],
          name: "getTotalUnits",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      ganacheUrl: "http://127.0.0.1:7545",
    };
  },
  methods: {
    async oracleUpdate() {
      let provider = new Web3(new Web3.providers.HttpProvider(this.ganacheUrl));
      provider.eth.getAccounts((error, result) => {
        console.log("Address", result);
      });
      //From metamask
      let AddressOwner = "0x2afAD5799Fd9F9FB2d2b80d5319cBF951232394f";
      //From Remix
      let contractAddress = "0xBCA5A40EaE68a2E4f6b2F67854daDf8A34F0d393";
      let contractInstance = new provider.eth.Contract(this.abi, contractAddress);
      console.log("Contract instance", contractInstance);

      // let result = await fetch("http://localhost:8089/");
      // let json = await result.json();
      // console.log(`Price: ${json.customerId}`);
      // console.log(`Volume: ${json.serialNumber}`);
      // console.log(`Volume: ${json.mpxn}`);
      // console.log(`Volume: ${json.totalUnits}`);
      // console.log(`Volume: ${json.lastMeterRead}`);

      let json = {
        customerId: "1234",
        serialNumber: "1234",
        mpxn: "1234",
        totalUnits: "1234",
        lastMeterRead: "12-12-2021"
      }

      //Call the contract to set a meter reading data
      contractInstance.methods
        .setMeterReading(parseInt(json.customerId), parseInt(json.serialNumber), parseInt(json.mpxn), parseInt(json.totalUnits), parseInt(json.lastMeterRead))
        .send({ from: AddressOwner })
        .on("receipt", () => {
          console.log("Values Updated");
        });

      //Call the contract to get the the meter readings
      contractInstance.methods
        .getSerialNumber(parseInt(json.customerId))
        .send({ from: AddressOwner })
        .then((val) => {
          console.log("Serial Number: ", val);
        });

      //Call the contract to get the stock volume
      contractInstance.methods
        .getMpxn(parseInt(json.customerId))
        .send({ from: AddressOwner })
        .then((val) => {
          console.log("mpxn: ", val);
        });

      //Call the contract to get the stock volume
      contractInstance.methods
        .getTotalUnits(parseInt(json.customerId))
        .send({ from: AddressOwner })
        .then((val) => {
          console.log("Total Units: ", val);
        });

      //Call the contract to get the stock volume
      contractInstance.methods
        .getLastMeterRead(parseInt(json.customerId))
        .send({ from: AddressOwner })
        .then((val) => {
          console.log("Last Meter Update Time: ", val);
        });

    },
  },
};
</script>
